# Generated by Django 3.1.7 on 2021-03-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_type',
            name='question',
            field=models.CharField(default='Question Text', max_length=500),
            preserve_default=False,
        ),
    ]
